import Vue from 'vue'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { library, config } from '@fortawesome/fontawesome-svg-core'
import {
  faShoppingCart as farShoppingCart,
  faBars,
  faCircleNotch,
  faCog,
  faSpinner,
  faDownload,
  faComments,
  faHeart,
  faPlus,
  faArrowDown,
  faCheck,
  faTimes,
  faEllipsisH,
  faEllipsisV,
  faEdit,
  faChevronLeft as farChevronLeft,
  faChevronRight as farChevronRight,
  faChevronDown,
  faChevronUp,
  faAngleUp,
  faAngleDown,
  faAngleRight,
  faSearch,
  faTags,
  faTrashAlt,
  faPencil,
  faUser,
  faUserPlus as farUserPlus,
  faUserLock,
  faComment as farComment,
  faEnvelope,
  faShareAlt,
  faForward as farForward,
  faBackward as farBackward,
  faCaretDown,
  faClipboard,
  faCogs,
  faExternalLink,
  faLongArrowRight,
  faPlay as farPlay,
  faPause as farPause,
  faEye,
  faEyeSlash,
  faSave,
  faSmile,
  faPeopleArrows,
  faMusic,
  faArrowRight,
  faLink,
  faInfoCircle,
  faLockAlt,
  faSignalStream,
  faBan,
  faHeadphonesAlt,
  faUsers,
  faClone,
  faMinus,
  faSignOut
} from '@fortawesome/pro-regular-svg-icons'

import {
  faFilter,
  faShoppingCart as fasShoppingCart,
  faPlay as fasPlay,
  faPlayCircle as fasPlayCircle,
  faPause as fasPause,
  faVolume,
  faVolumeUp,
  faVolumeDown,
  faVolumeMute,
  faForward as fasForward,
  faBackward as fasBackward,
  faChevronLeft as fasChevronLeft,
  faChevronRight as fasChevronRight,
  faTimesCircle,
  faQuestionCircle as fasQuestionCircle,
  faUserPlus as fasUserPlus,
  faComment as fasComment,
  faImage as fasImage,
  faPlus as fasPlus,
  faCheckCircle as fasCheckCircle
} from '@fortawesome/pro-solid-svg-icons'

import {
  faTwitter,
  faYoutube,
  faPaypal,
  faFacebook,
  faWhatsapp,
  faLinkedin,
  faPinterest,
  faStumbleupon,
  faTelegram,
  faVk
} from '@fortawesome/free-brands-svg-icons'

config.autoAddCss = false

library.add(
  farShoppingCart,
  fasShoppingCart,
  faBars,
  faFilter,
  fasShoppingCart,
  faCircleNotch,
  faCog,
  faSpinner,
  faDownload,
  faComments,
  farComment,
  fasComment,
  faEdit,
  faEnvelope,
  faHeart,
  faPlus,
  fasPlay,
  fasPause,
  farPlay,
  farPause,
  fasPlayCircle,
  faArrowDown,
  faCheck,
  faTimes,
  faEllipsisH,
  faEllipsisV,
  farChevronLeft,
  farChevronRight,
  fasChevronLeft,
  fasChevronRight,
  faLongArrowRight,
  faChevronDown,
  faChevronUp,
  faAngleUp,
  faAngleDown,
  faAngleRight,
  faSearch,
  faTags,
  faTrashAlt,
  faPencil,
  farUserPlus,
  fasUserPlus,
  faUser,
  faUserLock,
  faShareAlt,
  faEye,
  faEyeSlash,
  farForward,
  fasForward,
  farBackward,
  fasBackward,
  faCaretDown,
  faClipboard,
  faCogs,
  faExternalLink,
  faVolume,
  faVolumeUp,
  faVolumeDown,
  faVolumeMute,
  faSave,
  faTwitter,
  faYoutube,
  faPaypal,
  faFacebook,
  faWhatsapp,
  faLinkedin,
  faPinterest,
  faStumbleupon,
  faTelegram,
  faVk,
  faSmile,
  faMusic,
  faArrowRight,
  faPeopleArrows,
  faLink,
  faTimesCircle,
  faInfoCircle,
  faLockAlt,
  fasQuestionCircle,
  faSignalStream,
  faBan,
  fasImage,
  faHeadphonesAlt,
  faUsers,
  faClone,
  fasPlus,
  fasCheckCircle,
  faMinus,
  faSignOut
)

export default FontAwesomeIcon
